### PR TITLE
F capstone

### PR DESCRIPTION
**Pull request by Doheera-kosi**
### In this capstone project, the bellow was achieved;

- I build the homepages for both desktop and mobile versions.
- I build the about page for both desktop and mobile versions.
- Used media queries to scale from mobile version to desktop at a breakpoint of **768px** for both pages

## Interactions

- The home page has a link in the menu to the about page.
- The logo in the header links to the home page.

## Mobile menu
- When the user clicks (or taps) the hamburger button on the header, the mobile menu appears over the page.
- The mobile menu has a close (X) button that closes the menu.

## Dynamic page

- The section "Featured speakers" is created dynamically in JavaScript.
- JavaScript variables were used to store data about the speakers and when the page loads it creates the HTML for this section dynamically.

## Loom Video Link
- [Live Video Link](https://loom.com/share/15cc56f403fe49ff8cc356a4ed0af771)

### CODE REVIEW

**Review by frank1738 — CHANGES_REQUESTED** [review]
Hi @Doheera-kosi , 

Excellent job so far. Your project looks good!
There are some issues that you still need to work on to go to the next project but you are almost there!

YesYouAreGIF (2)


## Highlights

✅ Correct use of Github workflow
✅ No linter error
✅ README is okay
✅ Good Design👍 
✅ Descriptive PR👍


## Required Changes ♻️

- [REQUIRED] Kindly record a five-minute video using loom or any other tool walking us through your project. Remember that this is a project requirement and it is a good documentation practice

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by leonardodiasb — CHANGES_REQUESTED** [review]
# Required Changes ♻️ ⚠️ 🚦 

Hi @Doheera-kosi, 

Good job so far!
You still need to work on some issues to go to the next project, but you are almost there!

mario_ladders

## Good points 👍 

 - Nice CSS styling of your page. ✔️
 - No linters. ✔️ 

## Aspects to improve ♻️

- [x] Check the comments under the review.
- [ ] Your video presentation is good, but you missed highlighting a piece of code you built that you are really proud of. As this is a requirement of the project, I will ask you to record a new video containing this piece of code.
-
image


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

 - [OPTIONAL] The template footer design has a logo on the left and a piece of text on the right, and the desktop view of the about page has inverted colors(dark background and white text). It would be nice if you design your project with the same design of the template.
 - [OPTIONAL] You used some font-sizes with a `vw` value. This can make your pages not responsive and it's not a good practice to use it. It would be nice to change that.
 - [OPTIONAL] Your navbar is not responsive and on small desktop screen sizes, it can be larger than the browser viewport making elements disappear from the screen.
 - [OPTIONAL] The 'featured speakers' section is not center-aligned on desktop screen sizes close to the transition(around 800px wide). It would be great if this is centralized on the page.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by danmainah — CHANGES_REQUESTED** [review]
Hi @Doheera-kosi , 

Great work on making the changes requested by a previous reviewer 👏  👏 👏
You've done well implementing some of the requested changes, but there are still some which aren't been addressed yet.


 ## Highlights
✔️ No linter errors
✔️ Github flow was correctly used
✔️  Good design


 # Required Changes ♻️

- [ ] @Doheera-kosi  good work in your presentation but as previously requested, kindly add a video showcasing a piece of code you are proud of, your video shows different project sections, so it's hard to identify it unless you mention it in the video.
image
 

_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Lameck1** [comment]
This PR is under Second Opinion review

**Review by Lameck1 — APPROVED** [review]
Hello @Doheera-kosi  👋,

_This is an additional review as a result of the second opinion request._

About your concern: The video presentation looks good enough.

As this was the only reason that your project was not approved it will be approved as soon as possible.
Hold on and don't ask for another review in your Dashboard, you'll be able to submit this task ASAP.

Keep rocking 🚀!

**Pull request merged**
